# Generated by Django 4.1.8 on 2023-04-30 20:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, upload_to='profile_pics/%Y/%m/%d/')),
                ('name', models.TextField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True, verbose_name='bio')),
                ('phone_no', models.IntegerField(blank=True, null=True, verbose_name='phone_no')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
