# Generated by Django 4.1.8 on 2023-05-10 07:34

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_no',
            field=phone_field.models.PhoneField(blank=True, max_length=31, null=True, verbose_name='phone_no'),
        ),
    ]
