# Generated by Django 4.1.8 on 2023-04-10 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlog', '0018_alter_comment_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='approved',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
