# Generated by Django 4.1.8 on 2023-04-10 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlog', '0019_blogpost_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
