# Generated by Django 4.1.8 on 2023-04-10 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlog', '0020_alter_blogpost_approved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='approved',
            new_name='is_approved',
        ),
    ]
