# Generated by Django 4.1.8 on 2023-04-10 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlog', '0021_rename_approved_blogpost_is_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPostCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_title', models.CharField(max_length=255)),
            ],
        ),
    ]
