# Generated by Django 4.1.8 on 2023-04-14 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlog', '0026_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostcategories',
            name='slug',
            field=models.SlugField(blank=True, max_length=130),
        ),
    ]
