# Generated by Django 4.1.8 on 2023-04-16 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlog', '0029_blogpost_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='likes',
        ),
    ]
