# Generated by Django 4.1.8 on 2023-04-17 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlog', '0031_blogpost_dislikes_blogpost_likes_preference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='replycomment',
            name='replier_name',
        ),
        migrations.RemoveField(
            model_name='replycomment',
            name='reply_comment',
        ),
        migrations.AlterField(
            model_name='comment',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='MyBlog.comment'),
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='ReplyComment',
        ),
    ]
