# Generated by Django 4.1.8 on 2023-04-17 22:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MyBlog', '0034_alter_blogpost_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='viewers',
            field=models.ManyToManyField(editable=False, related_name='viewed_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
