# Generated by Django 4.1.8 on 2023-04-18 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlog', '0036_fileuploads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileuploads',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='profile_pics/%Y/%m/%d/'),
        ),
    ]
