# Generated by Django 4.1.8 on 2023-04-18 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlog', '0037_alter_fileuploads_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileuploads',
            old_name='image',
            new_name='file',
        ),
    ]
