# Generated by Django 4.1.8 on 2023-04-18 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlog', '0038_rename_image_fileuploads_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='image',
        ),
    ]
