# Generated by Django 4.1.8 on 2023-04-19 07:51

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlog', '0041_remove_comment_parent_comment_replycomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replycomment',
            name='reply_content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
