# Generated by Django 4.1.8 on 2023-04-19 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlog', '0042_alter_replycomment_reply_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='replycomment',
            old_name='reply_comment',
            new_name='comment',
        ),
    ]
