# Generated by Django 4.1.8 on 2023-04-20 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlog', '0043_rename_reply_comment_replycomment_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/%Y/%m/%d/'),
        ),
    ]
