# Generated by Django 4.1.8 on 2023-04-20 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlog', '0044_comment_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='image',
        ),
        migrations.CreateModel(
            name='CommentFileUploads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='profile_pics/%Y/%m/%d/')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyBlog.comment')),
            ],
        ),
    ]
