# Generated by Django 4.1.8 on 2023-04-22 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlog', '0047_typecategories_alter_blogpost_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostcategories',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MyBlog.typecategories'),
        ),
    ]
