# Generated by Django 4.1.8 on 2023-04-23 18:09

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlog', '0048_blogpostcategories_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='content'),
        ),
    ]
