# Generated by Django 4.1.8 on 2023-04-30 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlog', '0052_contact_delete_preference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='likes',
        ),
    ]
