# Generated by Django 4.1.8 on 2023-04-30 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MyBlog', '0055_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile_pics')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='bio')),
                ('phone_no', models.IntegerField(blank=True, null=True, verbose_name='phone_no')),
                ('facebook', models.CharField(blank=True, max_length=300, null=True, verbose_name='facebook')),
                ('instagram', models.CharField(blank=True, max_length=300, null=True, verbose_name='instagram')),
                ('linkedin', models.CharField(blank=True, max_length=300, null=True, verbose_name='linkedin')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
