# Generated by Django 4.1.8 on 2023-04-30 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlog', '0056_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
