# Generated by Django 4.1.8 on 2023-05-02 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlog', '0057_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='advert_pics/%Y/%m/%d/')),
                ('urllink', models.CharField(max_length=356, verbose_name='urllink')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('advertiser', models.CharField(max_length=356, verbose_name='advertiser')),
                ('expiration_date', models.DateTimeField(db_index=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyBlog.blogpostcategories')),
            ],
        ),
    ]
