# Generated by Django 4.1.8 on 2023-05-05 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0016_alter_user_following'),
        ('MyBlog', '0058_advertisement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
